import type { Metadata } from "next";
import{ Inter } from "next/font/google"
import { ConvexClientProvider } from "@/components/ConvexClientProvider";

import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";

import "./globals.css";

import { Models } from "@/components/models";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Parag App",
  description: "Generated by Parag Khirade",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
    <html lang="en">
      <body
        className={inter.className}
      >
        <ConvexClientProvider>
          <Models/>
        {children}  
        </ConvexClientProvider>
        
      </body>
    </html>
    </ConvexAuthNextjsServerProvider>
  );
}
